# import paths by importing utils paths.path
class Paths:
    """A class to hold paths for various datasets and vocabularies."""

    corpus_dir = "./corpora/"
    shakespeare_unclean = corpus_dir + "shakespeare.txt"
    shakespeare_clean_full = corpus_dir + "Shakespeare_clean_full.txt"
    shakespeare_clean_train = corpus_dir + "Shakespeare_clean_train.txt"
    shakespeare_clean_test = corpus_dir + "Shakespeare_clean_test.txt"
    shakespeare_clean_valid = corpus_dir + "Shakespeare_clean_valid.txt"
    sms_clean = corpus_dir + "sms_clean.txt"
    sms = corpus_dir + "sms.txt"
    vocab_dir = "./data/"
    sms_vocab_full_k250 = vocab_dir + "sms_vocab_full_k250.txt"
    sms_vocab_full_k500 = vocab_dir + "sms_vocab_full_k500.txt"
    sms_vocab_full_k750 = vocab_dir + "sms_vocab_full_k750.txt"
    vocab_full_k250 = vocab_dir + "vocab_full_k250.txt"
    vocab_full_k500 = vocab_dir + "vocab_full_k500.txt"
    vocab_full_k750 = vocab_dir + "vocab_full_k750.txt"
    vocab_full_k1000 = vocab_dir + "vocab_full_k1000.txt"
    vocab_full_k1250 = vocab_dir + "vocab_full_k1250.txt"
    vocab_full_k1500 = vocab_dir + "vocab_full_k1500.txt"
